version: "3.7"
services:
  nginx:
    image: nginx:latest
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./:/code
